image: golang:latest

before_script:
  - mkdir -p /go/src/github.com/acoustid
  - ln -s $CI_PROJECT_DIR /go/src/github.com/acoustid/go-acoustid
  - cd /go/src/github.com/acoustid/go-acoustid/

test:
  stage: test
  script:
    - go test -v ./{api,index,chromaprint,util}/...
  tags:
    - docker