image: golang:latest

before_script:
  - mkdir -p $GOPATH/src/github.com/acoustid
  - ln -s $CI_PROJECT_DIR $GOPATH/src/github.com/acoustid/go-acoustid
  - cd $GOPATH/src/github.com/acoustid/go-acoustid/

stages:
  - test
  - build

test:
  stage: test
  script:
    - make check
  tags:
    - docker

build:
  stage: build
  script:
    - make build
  tags:
    - docker
