image: golang:latest
cache:
  paths:
    - vendor/

before_script:
  - git submodule update --init --recursive
  - mkdir -p /go/src/github.com/acoustid
  - ln -s `pwd` /go/src/github.com/acoustid/go-acoustid
  - cd /go/src/github.com/acoustid/go-acoustid/

build:
  stage: build
  script:
    - go build -v ./{api,index,chromaprint,util}/...

test:
  stage: test
  script:
    - go test -v ./{api,index,chromaprint,util}/...
