name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v1

    - name: Test
      run: ./ci/test.sh

    - name: Build binaries
      run: ./ci/build.sh

    - name: Upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

  docker:
    name: Build Docker images
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Check out code
      uses: actions/checkout@v1
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'ref/tags/')

    - name: Download aindex binary
      uses: actions/download-artifact@v1
      with:
        name: dist
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'ref/tags/')

    - name: Build Docker images
      run: ./ci/build-images.sh
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'ref/tags/')

    - name: Push Docker images
      run: ./ci/push-images.sh
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'ref/tags/')
